### ISSUE TITLE
Eliminate RADICAL-Pilot dependency

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.analytics#10]
Currently, we depend on `rp.utils.get_session_description` and `rp.utils.get_session_profile`. These utilities should be migrated to `radical.utils` and made available to all the RADICAL-Cybertools.

I tag this as a bug because the dependency on RP breaks documentation, examples, and introduces a dependency on a specific RP branch.

**Comment by andre-merzky** [comment]
I can see why this breaks the abstraction layer -- but those methods indeed are RP specific.  For example, they expect a certain database layout to find a pilot sandbox, have the notion of pilots and units , look into the RP state model, etc.  I don't see a quick way to change that -- and would even argue that it might be unavoidable.  The resulting *analytics* session might be RP independent -- its creation not so much...

**Comment by andre-merzky** [comment]
```
s = ra.Session(sid='rp.session.1234', type='radical.pilot')
```

**Comment by andre-merzky** [comment]
This is now implemented.
