### ISSUE TITLE
Package Dependency list

### ISSUE THREAD

**Issue by benjha** [radical-cybertools/radical.analytics#123]
Hi Radical team,

It will be useful if adding an explicit package dependency  list for radical.analytics in README.md file. This will make conda based deployments faster for unsupported architectures such as ppc64le.

I think this should apply for all Radical software stack.

**Comment by andre-merzky** [comment]
Hi @benjha : the dependencies are listed in [setup.py](https://github.com/radical-cybertools/radical.analytics/blob/devel/setup.py#L226) - is conda not able to pick them up?

**Comment by benjha** [comment]
Hi Andre,

Yes it can, but in ppc64le, conda tries to compile the dependencies from scratch. This usually fails on Summit due its directory structure is not standard. So, it is easier to `conda install` the dependencies first, and then proceed with radical analytics.

For this case, having  a dependency list explicitly listed in `README.md` instead of looking for them in `setup.py`,   can make the deployment faster.

**Comment by mturilli** [comment]
This is now implemented in devel and will be released in July 2020
