### ISSUE TITLE
RTD build broken

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.analytics#163]
The RTD build seems to be broken lately - see https://readthedocs.org/projects/radicalanalytics/builds/16511144/ for an example.  @mturilli: could you please have a look?

**Comment by mturilli** [comment]
The auth error has been fixed but now the build fails possibly due to a change in RP/utils profiler? RA test sessions (created on Summit by Wenjie) seem not to be compatible with the current version. Error at: https://readthedocs.org/projects/radicalanalytics/builds/17109513/

**Comment by andre-merzky** [comment]
The error arises from this line:
```py
time_series = {pair: session.concurrency(event=pairs[pair]) for pair in pairs}
```
where `session` is not defined.  Alas the trace is not saying where that line comes from - do you know which notebook(s) contain it?

**Comment by andre-merzky** [comment]
This is fixed now.
