### ISSUE TITLE
Analytics cannot record 'resource_details' when pilot killed. 

### ISSUE THREAD

**Issue by okilic1** [radical-cybertools/radical.analytics#176]
It seems like when the pilot is killed by the system or with some issue; the .json file is missing information about "resource_details".

Json file:
```
 418             "resource": "ornl.summit_jsrun",
 419             "resource_details": null,
 420             "resource_sandbox": "file://localhost/gpfs/alpine/scratch/okilic1/med106/radical.pilot.sandbox",
```

**Comment by andre-merzky** [comment]
I would like to delay addressing this after the mongodb removal - the communication route for `resource_details` will change due to that anyway.  In fact a fix for this problem should be implicit in the mongodb removal branch.

**Comment by okilic1** [comment]
I think it is solved, I could not reproduce this issue with the new version that doesn't use MongoDB.
