### ISSUE TITLE
Issue with the concurrency (sampling)

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.analytics#180]
https://github.com/radical-cybertools/radical.analytics/blob/b0ce0773e51756cd1c6694973b05c3a3de8346a2/src/radical/analytics/session.py#L860-L865

shouldn't this code be as
```python
            t     = times[0][0]
            v     = collapsed[0][1]
            ret   = list()
            for time, val in collapsed:
                while time > t:
                    ret.append([t, v])
                    t += sampling
                v = val
```

when used the original code as `concurrency(event=events, sampling=1)` then had less concurrent tasks by 1 (`-1`) as it should be

**Comment by andre-merzky** [comment]
Nice catch,  correct I think...
