### ISSUE TITLE
`re.Pattern` is available in Python `>=3.7`

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.analytics#183]
One of the latest PRs https://github.com/radical-cybertools/radical.analytics/pull/179 introduced `re.Pattern` which is not in PY 3.6, thus we have the following failed CI job - https://github.com/radical-cybertools/radical.pilot/actions/runs/6712899409/job/18243440348

Is it a signal that we need to drop PY 3.6 support? or we can hide `re.Pattern` and not to use it for 3.6?

p.s. Amarel does support PY 3.6, but as well it provides 3.9, which we can enforce to use if we'll drop 3.6 support

**Comment by andre-merzky** [comment]
By now, even 3.7 is not an officially supported Python version anymore, and 3.8 will retire next year...  So yes, I am in favor of bumping the version requirements.  Let's discuss on the call...

**Comment by mtitov** [comment]
@andre-merzky Andre, can we add a patch to Analytics for now, thus not to break current RP tests

```python
            if uids:
                try: re_pattern = re.Pattern
                except AttributeError: re_pattern = None
                keep = False
                for uid in uids:
                    if re_pattern and isinstance(uid, re_pattern):
                        ...
                    else:
                        ...
```

**Comment by andre-merzky** [comment]
Yes, let's do that for now.

**Comment by AymenFJA** [comment]
Similar failure: https://github.com/radical-cybertools/radical.pilot/actions/runs/6741091910/job/18325152323?pr=3082
