### ISSUE TITLE
Wrong type in _initialize_entities

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.analytics#29]
I get the following error when I run `00_session_describe_rp.py rp.session.radical.mingtha.017204.0005`, where `rp.session.radical.mingtha.017204.0005
` is the `src_data_dir`. This directory has all of the log and json files as well.

I am running the following stack.
```
python            : 2.7.6
virtualenv        : /home/mingtha/ve/ve.exec_model_exp
radical.utils     : 0.44
saga-python       : v0.44-137-g98a692ed@experiment-aimes
radical.pilot     : v0.40.1-241-g8334834d@experiment-aimes
radical.analytics : v0.1-187-g56ecce7@experiment-aimes_nodata
```

Error:

```
Traceback (most recent call last):
  File "../../radical.analytics/examples/00_session_describe_rp.py", line 41, in <module>
    session = ra.Session(sid, 'radical.pilot', src=src)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/analytics/session.py", line 62, in __init__
    self._initialize_entities()
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/analytics/session.py", line 171, in _initialize_entities
    details['t_min']  = float(self._t_min)
TypeError: float() argument must be a string or a number
```

**Comment by mingtaiha** [comment]
I also get the same error with the following stack
```
python            : 2.7.6
virtualenv        : /home/mingtha/ve/ve.exec_model_exp
radical.utils     : v0.44.RC1-11-ge108e90@experiment-aimes
saga-python       : v0.44-137-g98a692ed@experiment-aimes
radical.pilot     : v0.40.1-241-g8334834d@experiment-aimes
radical.analytics : v0.1-187-g56ecce7@experiment-aimes_nodata
```

**Comment by mturilli** [comment]
Ping. This is now blocking Ming's experiments for his paper and the AIMES Experience one. We may want to have a look at it relatively soon.

**Comment by andre-merzky** [comment]
Hey Ming, 

can you please send me a tarball of the data set?  Also, are you bound to this specific stack (for the analysis), or could we in principle consider updating it?

**Comment by mturilli** [comment]
About the stack: Ming's experiments will distribute executions on both XSEDE HPC and OSG resources. As far as OSG branches have been merged into devel, he should be able to update to devel.

**Comment by andre-merzky** [comment]
Ming, I tried to find the data on the radical machine.  There is a dataset in `/home/mingtha/repos/execution_model_exp/experiment_aimes/supermic/rp.session.radical.mingtha.017204.0005` -- but that does not have any profiles.  Could that be the actual problem?  Of I am looking at the wrong dir, please do send me a tarball, or a pointer - thanks!

**Comment by mingtaiha** [comment]
I've migrated to a new `radical-stack`. I'll work with the new stack and open this ticket if necessary. We can consider this ticket obsolete for now.
