### ISSUE TITLE
No easy way to extract the starting time of the session

### ISSUE THREAD

**Issue by AA919** [radical-cybertools/radical.analytics#36]
(As discussed with Andre)
At the moment there is no easy way to extract the starting time of the session although this is very easy by reading the logs.

Cheers,

Alessio

**Comment by mturilli** [comment]
Related to #34

**Comment by ibethune** [comment]
Is this something which has never been possible i.e. new functionality?  In which case I would propose to defer if to the next release.

**Comment by AA919** [comment]
It is not a priority, therefore I would say yes. Andre and I decided to open this ticket to put a pin on it.
