### ISSUE TITLE
Error reading rows when creating Session object

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.analytics#53]
After the fix provided in #52, I no longer have a problem creating a Session object. However, I get the following errors when I try to create a Session object:

[ra_err.txt](https://github.com/radical-cybertools/radical.analytics/files/1333608/ra_err.txt)

 My `radical-stack`:
```
  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/mingtha/ve/ve.exec_model_exp

  radical.analytics    : v0.45.2-65-g66c0286@rc-v0.46.3
  radical.pilot        : 0.47-v0.46.2-124-g109e344d@rc-v0.46.3
  radical.utils        : 0.47-v0.46-45-gd67efa8@rc-v0.46.3
  saga                 : 0.47-v0.46-19-gcfba6e7f@debug-ming
```

**Comment by mingtaiha** [comment]
As per the RCT meeting, we discussed that I should try to use RA to look at a session that was created using the following `radical-stack`, but I still get the same error

```
  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/mingtha/ve/ve.exec_model_exp

  radical.analytics    : v0.45.2-65-g66c0286@rc-v0.46.3
  radical.pilot        : 0.47-v0.46.2-124-g109e344d@rc-v0.46.3
  radical.utils        : 0.47-v0.46-45-gd67efa8@rc-v0.46.3
  saga                 : 0.47-v0.46-19-gcfba6e7f@debug-ming
```

**Comment by mingtaiha** [comment]
As per requested: 
[rp.session.two.mingtha.017428.0000.zip](https://github.com/radical-cybertools/radical.analytics/files/1344934/rp.session.two.mingtha.017428.0000.zip)

**Comment by iparask** [comment]
I get this error just now

**Comment by andre-merzky** [comment]
Please make sure you pull again from the RC branches for RP and RU, and set

```
export RADICAL_ANALYTICS_LEGACY_PROFILES=TRUE
```

and try again.  Thanks!

**Comment by iparask** [comment]
I did and my unit duration is reported as 0. I will check in the profiles

**Comment by iparask** [comment]
The profiles look okay to me at least

**Comment by andre-merzky** [comment]
Please let me know what specific duration you try to get from what session (I assume the profiles attached above?)
