### ISSUE TITLE
Cannot read profiles from rc/0.46.3 branch

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.analytics#54]
I am getting the following error when I switch to 0.46.3 branch
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-eb66fb6c34d5> in <module>()
     17     print src
     18     #ttr, tte = get_entk_info(src)
---> 19     rp_dur, exec_dur = get_rp_info(src)
     20 
     21     #df.loc[str(pipelines)] = [ttr-tte,tte]

<ipython-input-5-b7b2a7085946> in get_rp_info(src)
     10     sid       = os.path.basename(json_file)[:-5]
     11 
---> 12     session = ra.Session(sid, 'radical.pilot', src=src)
     13     units = session.filter(etype='unit', inplace=False)
     14 

TypeError: __init__() got multiple values for keyword argument 'src'
```

You can find the notebook with the script and error at https://github.com/radical-collaboration/GB-SC18/blob/master/scripts/ties/plotme.ipynb.

The raw data (profiles) is available at https://github.com/radical-collaboration/GB-SC18/tree/master/scripts/ties/null_workload_8_replicas_vivek.

Also please see https://github.com/radical-cybertools/radical.utils/commit/45dd1bb08f0a6695d5283b9472f53fff833298ad#commitcomment-25381348. Not sure why the change in the order was required because this currently breaks the EnTK profiler.

**Comment by vivek-bala** [comment]
I am also not sure if the changes are consistent within a profile itself. For example see https://github.com/radical-collaboration/GB-SC18/blob/master/scripts/ties/null_workload_8_replicas_vivek/rp.session.js-17-212.jetstream-cloud.org.vivek91.017473.0004/pmgr.0000.prof.

The order of the head seems to be different from the order of the time entries in the following lines. The time entries seem to have (time,event,uid,comp,state,msg).

**Comment by vivek-bala** [comment]
I specified the stype and src in analytics(rc/0.46.3). I am getting the following error now:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-8-eb66fb6c34d5> in <module>()
     17     print src
     18     #ttr, tte = get_entk_info(src)
---> 19     rp_dur, exec_dur = get_rp_info(src)
     20 
     21     #df.loc[str(pipelines)] = [ttr-tte,tte]

<ipython-input-7-d4637c312a0f> in get_rp_info(src)
     10     sid       = os.path.basename(json_file)[:-5]
     11 
---> 12     session = ra.Session(stype='radical.pilot', src=src)
     13     units = session.filter(etype='unit', inplace=False)
     14 

/home/vivek/Research/tools/miniconda2/envs/ve-rp-rc/lib/python2.7/site-packages/radical/analytics/session.pyc in __init__(self, src, stype, sid, _entities, _init)
    107         self._entities = dict()
    108         if _init:
--> 109             self._initialize_entities(profile)
    110 
    111         # we do some bookkeeping in self._properties where we keep a list of

NameError: global name 'profile' is not defined
```

**Comment by andre-merzky** [comment]
This should be fixed in the RC branch now.  A merge did not correctly resolve (I think) and a variable rename got screwed up...

**Comment by vivek-bala** [comment]
This is fixed now.
