### ISSUE TITLE
CU event durations from agent component 

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.analytics#66]
For my `aprun` runs on Blue Waters I was looking for the following pre-executable events from the agent logs: 

```
cu_post_start       : cu shell script: pre-exec starts           (uid: uid, [CU_PRE])
cu_post_stop        : cu shell script: pre_exec stopped          (uid: uid, [CU_PRE])
```
(got these from [here](https://github.com/radical-cybertools/radical.pilot/blob/devel/docs/source/events.md#agentexecutingcomponent-component))

My agent logs don't appear to have these events...does `RP` handover to `aprun` before this event?

**Comment by andre-merzky** [comment]
Let me check.  What stack are you using?

**Comment by andre-merzky** [comment]
Uh, there is also a typo in the documentation - if you want `pre_exec` timings, you would use `cu_pre_start   / cu_pre_stop`.  I'll fix that - but can you please check if those exist?  Please also send me the  shell script for one of the units from the units sandbox, please.

**Comment by jdakka** [comment]
- Using `pypi` installation for entire stack. 

- `cu_pre_stop / cu_pre_start` are there 👍 

- These runs did not have the proper `STDOUT/STDERR/*.sh` files as noted in ticket [1564](https://github.com/radical-cybertools/radical.pilot/issues/1564)

**Comment by andre-merzky** [comment]
If you get `cu_pre_stop / cu_pre_start` in the profiles, we won't need the shell scripts.  I am not sure about the state of this ticket now though: is it solved with the correct event names, or do you see the events in the profiles, but can still not derive the durations with RA?  In the letter case, please attach a session (profiles + json) -- thanks!

**Comment by jdakka** [comment]
No worries. I can derive the events with RA. I'm creating pull request to update the [wrangler.py](https://github.com/radical-cybertools/radical.analytics/blob/devel/bin/radical-analytics-wrangler.py) 

It will contain the `pre-exec` events
