### ISSUE TITLE
unable to wrangle events

### ISSUE THREAD

**Issue by georgeha** [radical-cybertools/radical.analytics#68]
I am trying to wrangle events from these sessions. 

from mpi-exec only 3 sessins are wrangled (as I can see from the sessions.csv)
https://github.com/radical-experiments/rp_launch_methods/tree/master/analysis/data/exp-1-orte-mpi-exec

from the orte no sessions are wrangled. I am trying to reproduce the messages from the wrangler but I can't, because no new sessions are found. 

Any ideas? Thanks

**Comment by andre-merzky** [comment]
Can you please send the output of `radical-stack`, the wrangler command line, and any output you see?  Thanks!

**Comment by georgeha** [comment]
stack:
```

  python               : 2.7.14
  pythonpath           :
  virtualenv           : /home/george/ve

  radical.analytics    : v0.45.2-101-g8358b08@devel
  radical.pilot        : 0.47-0.47-14-gb1dff8bd@devel
  radical.utils        : 0.47.4
  saga                 : 0.47-v0.46-48-g5825f1b0@devel
```
from this directory:

rp_launch_methods/analysis/data/exp-1-orte-mpi-exec/mpi-exec 

radical-analytics-wrangler.py -d exp-mpi-exec/ -t exp

output:

```
Get raw sessions:
Done.


Marking sessions for wrangling:
No new sessions to wrangle found.
```

from this directory:

rp_launch_methods/analysis/data/exp-1-orte-mpi-exec/orte

radical-analytics-wrangler.py -d exp-orte -t exp

-same ouput. No new sessions found

**Comment by andre-merzky** [comment]
Thanks, that helps.  I won't manage to look at it today I'm afraid, but will ping back tomorrow evening.

**Comment by andre-merzky** [comment]
Some of your sessions don't have profiles, so analytics cannot find timestamps for events, and the error above is triggered for the first event in a pilot's life (getting into `NEW` state).:

```
 …/exp-1-orte-mpi-exec/mpi-exec/exp-mpi-exec  [master] $ for d in rp*; do ls -l $d/*.prof > /dev/null; done
ls: cannot access 'rp.session.one.george.017624.0007/*.prof': No such file or directory
ls: cannot access 'rp.session.one.george.017624.0008/*.prof': No such file or directory
ls: cannot access 'rp.session.one.george.017624.0009/*.prof': No such file or directory
ls: cannot access 'rp.session.one.george.017624.0010/*.prof': No such file or directory
ls: cannot access 'rp.session.one.george.017624.0011/*.prof': No such file or directory
ls: cannot access 'rp.session.one.george.017624.0012/*.prof': No such file or directory
```
