### ISSUE TITLE
Missing profiles

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.analytics#69]
I have several RP runs that finish but do not contain `.prof`. 

```
radical.entk         : 0.6.1
radical.pilot         : 0.47.8
radical.utils         : 0.47.4
saga                    : 0.47.3
```
I set my `env` variables accordingly: 

```
export RADICAL_PILOT_PROFILE=True
export RADICAL_ENMD_PROFILE=True
export RADICAL_ENMD_PROFILING=1
export RP_ENABLE_OLD_DEFINES=True

```

I tried to manually do `radicalpilot-fetch-profiles` but no good...I've attached an example of the client logs and the run_logs i.e. `debug.log`

The only profile I have is `bootstrap.prof`

[esmacs_2_run_1.zip](https://github.com/radical-cybertools/radical.analytics/files/1936234/esmacs_2_run_1.zip)

In case you need agent logs on Blue Waters: 

`/u/sciteam/dakka/scratch/radical.pilot.sandbox/rp.session.two.jdakka.017642.0009/pilot.0000`

**Comment by SrinivasMushnoori** [comment]
I have the exact same issue.

**Comment by jdakka** [comment]
@SrinivasMushnoori misery needs company 😄

**Comment by andre-merzky** [comment]
Yes, it likely is.  I am working on a clean fix, and should be able to merge/release that later today (April 23), but meanwhile, setting `RADICAL_PROFILE` should work.  @SrinivasMushnoori though observes that pilot side profiles are *still* missing then - as a workaround, please add `export RADICAL_PROFILE=True` in your `~/.bashrc` on the *target* resource.

**Comment by SrinivasMushnoori** [comment]
Testing now with `export RADICAL_PROFILE=True` in `~/.bashrc`

Will report with results shortly.

**Comment by jdakka** [comment]
I tested on BW and I am getting profiles by setting the env in my ~/.bashrc... @andre-merzky I wasn't aware that additional profiles env variable have to be set besides `export RADICAL_PILOT_PROFILE=True`. Was it intentional to have `export RADICAL_PROFILE=True` ?

**Comment by andre-merzky** [comment]
This is a regression, and not intentional :(
