### ISSUE TITLE
Release feature/entk-integration branch

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.analytics#77]
I and few others have been using the feature/entk-integration branch for a while, I think this branch can merged and released.

@andre-merzky do you see anything specific that needs to be added/changed before releasing?

**Comment by andre-merzky** [comment]
Uhm, do you mean [this one](https://github.com/radical-cybertools/radical.analytics/pull/46)?  This is merged since almost one year ... ;-)

**Comment by vivek-bala** [comment]
I don't think that is merged with master and release though, see [here](https://github.com/radical-cybertools/radical.analytics/compare/master...feature/entk-integration#diff-9999acfde7534787968eeac9720d8e4aL91). It is not merged with devel either, IIUC.

**Comment by andre-merzky** [comment]
Indeed - there are commits made on the branch after the merge.  I probably should have removed the branch, apologies.  Either way, yes, that can be merged again, will do!

**Comment by vivek-bala** [comment]
Ah okay, good to know where the sync-miss was. I will do the same for any branches in EnTK. Thanks!

**Comment by vivek-bala** [comment]
Bump, I think this is still pending. Just a reminder.
