### ISSUE TITLE
Descriptive warnings

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.analytics#8]
When some data is missing from the profiles/json, a more or less generic warning is issued. 

For example:
```
sid: rp.session.radical.mingtha.017035.0010
WARNING: no time offset for radical:144.76.72.175
```
It would be desirable to have more descriptive (i.e., what is the problem)/informative (i.e., where to look for to isolate the issue) warning.

**Comment by andre-merzky** [comment]
I hope this is more descriptive now:

```
unsynced profile /home/merzky/radical/radical.analytics.devel/rp.session.thinkie.merzky.017044.0000/pilot.0000/bootstrap_1.prof
unsynced hosts: ['thinkie:10.0.0.4']
```

which is printed while parsing profiles.  Any other suggestion?
