### ISSUE TITLE
Unable to run radical analytics get_duration.py for Entk session

### ISSUE THREAD

**Issue by divyaprakash0426** [radical-cybertools/radical.analytics#83]
Traceback (most recent call last):
  File "get_durations.py", line 27, in <module>
    session = ra.Session(src=src, sid = sid, stype='radical.entk')
  File "/home/divyaprakash/EnTK/local/lib/python2.7/site-packages/radical/analytics/session.py", line 131, in __init__
    self._initialize_entities(self._profile)
  File "/home/divyaprakash/EnTK/local/lib/python2.7/site-packages/radical/analytics/session.py", line 235, in _initialize_entities
    details = self._description['tree'].get(uid, dict())
KeyError: 'tree'

**Comment by divyaprakash0426** [comment]
Yes. I have the profiles in the appropriate directory and I have specified the directory location in the get_duration.py file. When I run the get_duration.py file to get the details of my entk session, I get the above error.

**Comment by vivek-bala** [comment]
Can you share the version of EnTK that you used to generate the profiles? Is this the same as the one you are using to analyze them?

**Comment by divyaprakash0426** [comment]
This is my radical stack:
python               : 2.7.15rc1
  pythonpath           : 
  virtualenv           : /home/divyaprakash/EnTK

  radical.analytics    : 0.50.1
  radical.entk         : 0.7.8
  radical.pilot        : 0.50.17
  radical.utils        : 0.50.2
  saga                 : 0.50.1

**Comment by vivek-bala** [comment]
Ah okay. Can you run ```pip install radical.entk --upgrade``` after activating your virtualenv please? The current version of EnTK is 0.7.10 and this issue should be resolved in it.

**Comment by divyaprakash0426** [comment]
Thank you!! It works now

**Comment by vivek-bala** [comment]
Awesome! Closing this ticket since it is resolved.
